2020-08-10 17:24:31,235 ERROR: Exception on /auth/reset_password_request [POST] [in d:\MicroBlog\micro\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\MicroBlog\micro\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\MicroBlog\app\auth\routes.py", line 62, in reset_password_request
    send_password_reset_email(user)
  File "D:\MicroBlog\app\auth\email.py", line 14, in send_password_reset_email
    html_body=render_template('email/reset_password.html',
  File "d:\MicroBlog\micro\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "d:\MicroBlog\micro\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "d:\MicroBlog\micro\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "d:\MicroBlog\micro\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "d:\MicroBlog\micro\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\MicroBlog\app\templates\email\reset_password.html", line 5, in top-level template code
    <a href="{{ url_for('reset_password', token=token, _external=True) }}">
  File "d:\MicroBlog\micro\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\MicroBlog\micro\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\MicroBlog\micro\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "d:\MicroBlog\micro\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'auth.reset_password' instead?
2020-08-10 17:30:56,431 INFO: Microblog startup [in D:\MicroBlog\app\__init__.py:81]
2020-08-10 17:38:52,547 ERROR: Exception on /search [GET] [in d:\MicroBlog\micro\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\MicroBlog\micro\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\MicroBlog\micro\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\MicroBlog\app\main\routes.py", line 175, in search
    posts, total = Post.search(g.search_form.q.data, page, current_app.config['POSTS_PER_PAGE'])
  File "D:\MicroBlog\app\models.py", line 93, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
TypeError: cannot unpack non-iterable NoneType object
2020-08-10 19:00:06,993 INFO: Microblog startup [in D:\MicroBlog\app\__init__.py:81]
2020-08-10 19:00:23,369 ERROR: Exception on /search [GET] [in d:\MicroBlog\micro\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\MicroBlog\micro\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\MicroBlog\micro\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\MicroBlog\app\main\routes.py", line 167, in search
    posts, total = Post.search(g.search_form.q.data, page,
  File "D:\MicroBlog\app\models.py", line 15, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
TypeError: cannot unpack non-iterable NoneType object
2020-08-10 19:03:22,489 INFO: Microblog startup [in D:\MicroBlog\app\__init__.py:81]
2020-08-10 19:03:38,444 ERROR: Exception on /search [GET] [in d:\MicroBlog\micro\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\MicroBlog\micro\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\MicroBlog\micro\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\MicroBlog\app\main\routes.py", line 167, in search
    posts, total = Post.search(g.search_form.q.data, page,
  File "D:\MicroBlog\app\models.py", line 20, in search
    for i in range(len(ids)):
TypeError: object of type 'NoneType' has no len()
2020-08-10 19:05:34,405 INFO: Microblog startup [in D:\MicroBlog\app\__init__.py:81]
2020-08-10 19:05:53,057 ERROR: Exception on /search [GET] [in d:\MicroBlog\micro\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\MicroBlog\micro\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\MicroBlog\micro\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\MicroBlog\app\main\routes.py", line 167, in search
    posts = Post.search(g.search_form.q.data, page,
  File "D:\MicroBlog\app\models.py", line 20, in search
    for i in range(len(ids)):
TypeError: object of type 'NoneType' has no len()
